/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgetPasswordRouteImport } from './routes/_auth/forget-password'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppTabsKbaseRouteImport } from './routes/_app/_tabs/kbase'
import { Route as AppTabsInventoryRouteImport } from './routes/_app/_tabs/inventory'
import { Route as AppTabsConversationsRouteImport } from './routes/_app/_tabs/conversations'
import { Route as AppTabsConnectorsRouteImport } from './routes/_app/_tabs/connectors'
import { Route as AppTabsAnalyticsRouteImport } from './routes/_app/_tabs/analytics'
import { Route as AppSettingsUserpermissionsRouteImport } from './routes/_app/_settings/userpermissions'
import { Route as AppSettingsSupportRouteImport } from './routes/_app/_settings/support'
import { Route as AppSettingsProfileRouteRouteImport } from './routes/_app/_settings/profile/route'
import { Route as AppSettingsProfileUserinfoRouteImport } from './routes/_app/_settings/profile/userinfo'
import { Route as AppSettingsProfilePrivacyRouteImport } from './routes/_app/_settings/profile/privacy'
import { Route as AppSettingsProfileBusinessinfoRouteImport } from './routes/_app/_settings/profile/businessinfo'
import { Route as AppSettingsProfileBillingRouteImport } from './routes/_app/_settings/profile/billing'
import { Route as AppSettingsProfileAiconfigRouteImport } from './routes/_app/_settings/profile/aiconfig'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/_auth/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTabsKbaseRoute = AppTabsKbaseRouteImport.update({
  id: '/_tabs/kbase',
  path: '/kbase',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTabsInventoryRoute = AppTabsInventoryRouteImport.update({
  id: '/_tabs/inventory',
  path: '/inventory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTabsConversationsRoute = AppTabsConversationsRouteImport.update({
  id: '/_tabs/conversations',
  path: '/conversations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTabsConnectorsRoute = AppTabsConnectorsRouteImport.update({
  id: '/_tabs/connectors',
  path: '/connectors',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTabsAnalyticsRoute = AppTabsAnalyticsRouteImport.update({
  id: '/_tabs/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsUserpermissionsRoute =
  AppSettingsUserpermissionsRouteImport.update({
    id: '/_settings/userpermissions',
    path: '/userpermissions',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsSupportRoute = AppSettingsSupportRouteImport.update({
  id: '/_settings/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsProfileRouteRoute = AppSettingsProfileRouteRouteImport.update({
  id: '/_settings/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsProfileUserinfoRoute =
  AppSettingsProfileUserinfoRouteImport.update({
    id: '/userinfo',
    path: '/userinfo',
    getParentRoute: () => AppSettingsProfileRouteRoute,
  } as any)
const AppSettingsProfilePrivacyRoute =
  AppSettingsProfilePrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AppSettingsProfileRouteRoute,
  } as any)
const AppSettingsProfileBusinessinfoRoute =
  AppSettingsProfileBusinessinfoRouteImport.update({
    id: '/businessinfo',
    path: '/businessinfo',
    getParentRoute: () => AppSettingsProfileRouteRoute,
  } as any)
const AppSettingsProfileBillingRoute =
  AppSettingsProfileBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppSettingsProfileRouteRoute,
  } as any)
const AppSettingsProfileAiconfigRoute =
  AppSettingsProfileAiconfigRouteImport.update({
    id: '/aiconfig',
    path: '/aiconfig',
    getParentRoute: () => AppSettingsProfileRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/profile': typeof AppSettingsProfileRouteRouteWithChildren
  '/support': typeof AppSettingsSupportRoute
  '/userpermissions': typeof AppSettingsUserpermissionsRoute
  '/analytics': typeof AppTabsAnalyticsRoute
  '/connectors': typeof AppTabsConnectorsRoute
  '/conversations': typeof AppTabsConversationsRoute
  '/inventory': typeof AppTabsInventoryRoute
  '/kbase': typeof AppTabsKbaseRoute
  '/profile/aiconfig': typeof AppSettingsProfileAiconfigRoute
  '/profile/billing': typeof AppSettingsProfileBillingRoute
  '/profile/businessinfo': typeof AppSettingsProfileBusinessinfoRoute
  '/profile/privacy': typeof AppSettingsProfilePrivacyRoute
  '/profile/userinfo': typeof AppSettingsProfileUserinfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/profile': typeof AppSettingsProfileRouteRouteWithChildren
  '/support': typeof AppSettingsSupportRoute
  '/userpermissions': typeof AppSettingsUserpermissionsRoute
  '/analytics': typeof AppTabsAnalyticsRoute
  '/connectors': typeof AppTabsConnectorsRoute
  '/conversations': typeof AppTabsConversationsRoute
  '/inventory': typeof AppTabsInventoryRoute
  '/kbase': typeof AppTabsKbaseRoute
  '/profile/aiconfig': typeof AppSettingsProfileAiconfigRoute
  '/profile/billing': typeof AppSettingsProfileBillingRoute
  '/profile/businessinfo': typeof AppSettingsProfileBusinessinfoRoute
  '/profile/privacy': typeof AppSettingsProfilePrivacyRoute
  '/profile/userinfo': typeof AppSettingsProfileUserinfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/forget-password': typeof AuthForgetPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/_settings/profile': typeof AppSettingsProfileRouteRouteWithChildren
  '/_app/_settings/support': typeof AppSettingsSupportRoute
  '/_app/_settings/userpermissions': typeof AppSettingsUserpermissionsRoute
  '/_app/_tabs/analytics': typeof AppTabsAnalyticsRoute
  '/_app/_tabs/connectors': typeof AppTabsConnectorsRoute
  '/_app/_tabs/conversations': typeof AppTabsConversationsRoute
  '/_app/_tabs/inventory': typeof AppTabsInventoryRoute
  '/_app/_tabs/kbase': typeof AppTabsKbaseRoute
  '/_app/_settings/profile/aiconfig': typeof AppSettingsProfileAiconfigRoute
  '/_app/_settings/profile/billing': typeof AppSettingsProfileBillingRoute
  '/_app/_settings/profile/businessinfo': typeof AppSettingsProfileBusinessinfoRoute
  '/_app/_settings/profile/privacy': typeof AppSettingsProfilePrivacyRoute
  '/_app/_settings/profile/userinfo': typeof AppSettingsProfileUserinfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forget-password'
    | '/login'
    | '/signup'
    | '/profile'
    | '/support'
    | '/userpermissions'
    | '/analytics'
    | '/connectors'
    | '/conversations'
    | '/inventory'
    | '/kbase'
    | '/profile/aiconfig'
    | '/profile/billing'
    | '/profile/businessinfo'
    | '/profile/privacy'
    | '/profile/userinfo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forget-password'
    | '/login'
    | '/signup'
    | '/profile'
    | '/support'
    | '/userpermissions'
    | '/analytics'
    | '/connectors'
    | '/conversations'
    | '/inventory'
    | '/kbase'
    | '/profile/aiconfig'
    | '/profile/billing'
    | '/profile/businessinfo'
    | '/profile/privacy'
    | '/profile/userinfo'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_auth/forget-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/_settings/profile'
    | '/_app/_settings/support'
    | '/_app/_settings/userpermissions'
    | '/_app/_tabs/analytics'
    | '/_app/_tabs/connectors'
    | '/_app/_tabs/conversations'
    | '/_app/_tabs/inventory'
    | '/_app/_tabs/kbase'
    | '/_app/_settings/profile/aiconfig'
    | '/_app/_settings/profile/billing'
    | '/_app/_settings/profile/businessinfo'
    | '/_app/_settings/profile/privacy'
    | '/_app/_settings/profile/userinfo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forget-password': {
      id: '/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_tabs/kbase': {
      id: '/_app/_tabs/kbase'
      path: '/kbase'
      fullPath: '/kbase'
      preLoaderRoute: typeof AppTabsKbaseRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_tabs/inventory': {
      id: '/_app/_tabs/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppTabsInventoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_tabs/conversations': {
      id: '/_app/_tabs/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AppTabsConversationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_tabs/connectors': {
      id: '/_app/_tabs/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppTabsConnectorsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_tabs/analytics': {
      id: '/_app/_tabs/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppTabsAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_settings/userpermissions': {
      id: '/_app/_settings/userpermissions'
      path: '/userpermissions'
      fullPath: '/userpermissions'
      preLoaderRoute: typeof AppSettingsUserpermissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_settings/support': {
      id: '/_app/_settings/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSettingsSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_settings/profile': {
      id: '/_app/_settings/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_settings/profile/userinfo': {
      id: '/_app/_settings/profile/userinfo'
      path: '/userinfo'
      fullPath: '/profile/userinfo'
      preLoaderRoute: typeof AppSettingsProfileUserinfoRouteImport
      parentRoute: typeof AppSettingsProfileRouteRoute
    }
    '/_app/_settings/profile/privacy': {
      id: '/_app/_settings/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof AppSettingsProfilePrivacyRouteImport
      parentRoute: typeof AppSettingsProfileRouteRoute
    }
    '/_app/_settings/profile/businessinfo': {
      id: '/_app/_settings/profile/businessinfo'
      path: '/businessinfo'
      fullPath: '/profile/businessinfo'
      preLoaderRoute: typeof AppSettingsProfileBusinessinfoRouteImport
      parentRoute: typeof AppSettingsProfileRouteRoute
    }
    '/_app/_settings/profile/billing': {
      id: '/_app/_settings/profile/billing'
      path: '/billing'
      fullPath: '/profile/billing'
      preLoaderRoute: typeof AppSettingsProfileBillingRouteImport
      parentRoute: typeof AppSettingsProfileRouteRoute
    }
    '/_app/_settings/profile/aiconfig': {
      id: '/_app/_settings/profile/aiconfig'
      path: '/aiconfig'
      fullPath: '/profile/aiconfig'
      preLoaderRoute: typeof AppSettingsProfileAiconfigRouteImport
      parentRoute: typeof AppSettingsProfileRouteRoute
    }
  }
}

interface AppSettingsProfileRouteRouteChildren {
  AppSettingsProfileAiconfigRoute: typeof AppSettingsProfileAiconfigRoute
  AppSettingsProfileBillingRoute: typeof AppSettingsProfileBillingRoute
  AppSettingsProfileBusinessinfoRoute: typeof AppSettingsProfileBusinessinfoRoute
  AppSettingsProfilePrivacyRoute: typeof AppSettingsProfilePrivacyRoute
  AppSettingsProfileUserinfoRoute: typeof AppSettingsProfileUserinfoRoute
}

const AppSettingsProfileRouteRouteChildren: AppSettingsProfileRouteRouteChildren =
  {
    AppSettingsProfileAiconfigRoute: AppSettingsProfileAiconfigRoute,
    AppSettingsProfileBillingRoute: AppSettingsProfileBillingRoute,
    AppSettingsProfileBusinessinfoRoute: AppSettingsProfileBusinessinfoRoute,
    AppSettingsProfilePrivacyRoute: AppSettingsProfilePrivacyRoute,
    AppSettingsProfileUserinfoRoute: AppSettingsProfileUserinfoRoute,
  }

const AppSettingsProfileRouteRouteWithChildren =
  AppSettingsProfileRouteRoute._addFileChildren(
    AppSettingsProfileRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsProfileRouteRoute: typeof AppSettingsProfileRouteRouteWithChildren
  AppSettingsSupportRoute: typeof AppSettingsSupportRoute
  AppSettingsUserpermissionsRoute: typeof AppSettingsUserpermissionsRoute
  AppTabsAnalyticsRoute: typeof AppTabsAnalyticsRoute
  AppTabsConnectorsRoute: typeof AppTabsConnectorsRoute
  AppTabsConversationsRoute: typeof AppTabsConversationsRoute
  AppTabsInventoryRoute: typeof AppTabsInventoryRoute
  AppTabsKbaseRoute: typeof AppTabsKbaseRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsProfileRouteRoute: AppSettingsProfileRouteRouteWithChildren,
  AppSettingsSupportRoute: AppSettingsSupportRoute,
  AppSettingsUserpermissionsRoute: AppSettingsUserpermissionsRoute,
  AppTabsAnalyticsRoute: AppTabsAnalyticsRoute,
  AppTabsConnectorsRoute: AppTabsConnectorsRoute,
  AppTabsConversationsRoute: AppTabsConversationsRoute,
  AppTabsInventoryRoute: AppTabsInventoryRoute,
  AppTabsKbaseRoute: AppTabsKbaseRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
